[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Ignore files that should not be deployed
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
