# ==================== KUBERNETES SECRETS ====================
apiVersion: v1
kind: Secret
metadata:
  name: omnilife-secrets
  namespace: omnilife
type: Opaque
data:
  # ==================== DATABASE SECRETS ====================
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)
  
  # ==================== APPLICATION SECRETS ====================
  SECRET_KEY: b21uaWxpZmUtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # omnilife-secret-key-change-in-production (base64 encoded)
  
  # ==================== EXTERNAL SERVICE SECRETS ====================
  # Add your external service API keys here
  # Example: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, etc.
  
  # ==================== MONITORING SECRETS ====================
  GRAFANA_ADMIN_PASSWORD: YWRtaW4=  # admin (base64 encoded)
