"""Initial database schema

Revision ID: 65616977cc33
Revises: 
Create Date: 2025-08-30 18:46:25.696208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65616977cc33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_id'), 'marketplace_products', ['id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('action_text', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('insight_metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_table('travel_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_plans_id'), 'travel_plans', ['id'], unique=False)
    op.drop_index('ix_fitness_workouts_id', table_name='fitness_workouts')
    op.drop_table('fitness_workouts')
    op.drop_index('ix_verification_codes_id', table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index('ix_finance_budgets_id', table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index('ix_finance_goals_id', table_name='finance_goals')
    op.drop_table('finance_goals')
    op.drop_index('ix_fitness_measurements_id', table_name='fitness_measurements')
    op.drop_table('fitness_measurements')
    op.add_column('finance_accounts', sa.Column('account_type', sa.String(length=100), nullable=False))
    op.alter_column('finance_accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('finance_accounts', 'type')
    op.add_column('finance_transactions', sa.Column('transaction_type', sa.String(length=50), nullable=False))
    op.alter_column('finance_transactions', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_column('finance_transactions', 'type')
    op.drop_column('finance_transactions', 'user_id')
    op.add_column('fitness_goals', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('fitness_goals', sa.Column('goal_type', sa.String(length=100), nullable=False))
    op.add_column('fitness_goals', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('fitness_goals', 'unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('fitness_goals', 'progress_percentage')
    op.drop_column('fitness_goals', 'status')
    op.drop_column('fitness_goals', 'description')
    op.drop_column('fitness_goals', 'type')
    op.drop_column('fitness_goals', 'name')
    op.add_column('user_sessions', sa.Column('session_token', sa.String(length=255), nullable=False))
    op.drop_index('ix_user_sessions_refresh_token', table_name='user_sessions')
    op.drop_index('ix_user_sessions_token', table_name='user_sessions')
    op.create_unique_constraint(None, 'user_sessions', ['session_token'])
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'refresh_token')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'token')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'location')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_guest')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('is_guest', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'status')
    op.drop_column('users', 'full_name')
    op.add_column('user_sessions', sa.Column('token', sa.VARCHAR(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('user_agent', sa.TEXT(), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_token', sa.VARCHAR(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.create_index('ix_user_sessions_token', 'user_sessions', ['token'], unique=False)
    op.create_index('ix_user_sessions_refresh_token', 'user_sessions', ['refresh_token'], unique=False)
    op.drop_column('user_sessions', 'session_token')
    op.add_column('fitness_goals', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('fitness_goals', sa.Column('type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('fitness_goals', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('fitness_goals', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.add_column('fitness_goals', sa.Column('progress_percentage', sa.FLOAT(), nullable=True))
    op.alter_column('fitness_goals', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('fitness_goals', 'is_completed')
    op.drop_column('fitness_goals', 'goal_type')
    op.drop_column('fitness_goals', 'title')
    op.add_column('finance_transactions', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('finance_transactions', sa.Column('type', sa.VARCHAR(length=20), nullable=True))
    op.create_foreign_key(None, 'finance_transactions', 'users', ['user_id'], ['id'])
    op.alter_column('finance_transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('finance_transactions', 'transaction_type')
    op.add_column('finance_accounts', sa.Column('type', sa.VARCHAR(length=50), nullable=True))
    op.alter_column('finance_accounts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('finance_accounts', 'account_type')
    op.create_table('fitness_measurements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fitness_measurements_id', 'fitness_measurements', ['id'], unique=False)
    op.create_table('finance_goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('target_amount', sa.FLOAT(), nullable=False),
    sa.Column('current_amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=True),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_goals_id', 'finance_goals', ['id'], unique=False)
    op.create_table('finance_budgets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('spent', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_budgets_id', 'finance_budgets', ['id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('code_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_codes_id', 'verification_codes', ['id'], unique=False)
    op.create_table('fitness_workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('calories_burned', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fitness_workouts_id', 'fitness_workouts', ['id'], unique=False)
    op.drop_index(op.f('ix_travel_plans_id'), table_name='travel_plans')
    op.drop_table('travel_plans')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_marketplace_products_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    # ### end Alembic commands ###
